-- ============================================================================
-- 01_dump_org_schema.sql  ·  conventity.com bootstrap — Faz A KEŞİF
--
-- NE YAPAR: conventity.ORG Supabase projesindeki `public` şemasının tam DDL'ini
--           metin olarak döker. Veri DÖKMEZ, hiçbir şeyi DEĞİŞTİRMEZ.
--           Tek bir `select` — salt okunur.
--
-- NEREDE ÇALIŞIR: conventity.ORG projesi (shbwylrwpioqypbdhjgn) → SQL Editor.
--                 conventity-prod'da (yeni, boş proje) ÇALIŞTIRMA — orada
--                 dökülecek bir şey yok.
--
-- SONRA NE OLUR: çıktı (tek kolon, sıralı) Claude'a verilir; Claude bundan
--                temiz kurulum için seed'siz, idempotent tek dosya üretir.
--
-- KULLANIM: tamamını SQL Editor'e yapıştır → Run → sonuç tablosunun sağ
--           üstünden "Download CSV" → dosyayı paylaş.
--           (Ekrandan kopyalama uzun satırları kırpabilir; CSV güvenli.)
-- ============================================================================

with

/* ---- 0) eklentiler (bilgi amaçlı — yorum satırı olarak dökülür) -----------
   Yeni Supabase projesi kendi varsayılan eklentileriyle gelir; körlemesine
   `create extension` çalıştırmak şema/sürüm çakışması yaratabilir. Bu yüzden
   yorum olarak dökülüp hangisinin gerçekten gerektiğine sonra karar verilir. */
exts as (
  select e.extname as obj,
         '--   ' || rpad(e.extname, 28) || ' schema=' || n.nspname ||
         '  v' || e.extversion as ddl
  from pg_extension e
  join pg_namespace n on n.oid = e.extnamespace
  where e.extname <> 'plpgsql'
),

/* ---- 1) kullanıcı tipleri (enum/domain) ---------------------------------- */
types as (
  select t.typname as obj,
         'create type public.' || quote_ident(t.typname) || ' as enum (' ||
         (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
            from pg_enum e where e.enumtypid = t.oid) || ');' as ddl
  from pg_type t
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' and t.typtype = 'e'
),

/* ---- 2) diziler (serial kolonların bağımlılığı) --------------------------
   identity kolonlarin dizisi haric: onu `generated ... as identity` clause'u
   tablo kurulurken kendisi yaratir (pg_depend deptype='i'). Dokersek replay'de
   ikinci bir ..._seq1 dogar. serial'in dizisi (deptype='a') ise gerekli.      */
seqs as (
  select c.relname as obj,
         'create sequence if not exists public.' || quote_ident(c.relname) || ';' as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'S'
    and not exists (
      select 1 from pg_depend d
      where d.objid = c.oid
        and d.classid = 'pg_class'::regclass
        and d.refclassid = 'pg_class'::regclass
        and d.deptype = 'i'
    )
),

/* ---- 3) tablolar + kolonlar ---------------------------------------------- */
tbls as (
  select c.relname as obj,
         'create table if not exists public.' || quote_ident(c.relname) || E' (\n' ||
         string_agg(
           '  ' || quote_ident(a.attname) || ' ' ||
           format_type(a.atttypid, a.atttypmod) ||
           case
             when a.attidentity = 'a' then ' generated always as identity'
             when a.attidentity = 'd' then ' generated by default as identity'
             when a.attgenerated = 's'
               then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
             when ad.adbin is not null
               then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
             else ''
           end ||
           case when a.attnotnull then ' not null' else '' end,
           E',\n' order by a.attnum
         ) || E'\n);' as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  group by c.relname
),

/* ---- 4) PK / UNIQUE / CHECK ---------------------------------------------- */
cons as (
  select rel.relname as obj, con.conname as cname,
         'alter table public.' || quote_ident(rel.relname) ||
         ' add constraint ' || quote_ident(con.conname) || ' ' ||
         pg_get_constraintdef(con.oid) || ';' as ddl
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public' and con.contype in ('p','u','c')
),

/* ---- 5) yabancı anahtarlar (en sonda — hedef tablolar kurulmuş olsun) ----- */
fks as (
  select rel.relname as obj, con.conname as cname,
         'alter table public.' || quote_ident(rel.relname) ||
         ' add constraint ' || quote_ident(con.conname) || ' ' ||
         pg_get_constraintdef(con.oid) || ';' as ddl
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public' and con.contype = 'f'
),

/* ---- 6) indeksler (kısıt arkasındakiler hariç) --------------------------- */
idx as (
  select i.tablename as obj, i.indexname as iname, i.indexdef || ';' as ddl
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (
      select 1 from pg_constraint con
      join pg_class ic on ic.oid = con.conindid
      where ic.relname = i.indexname and con.contype in ('p','u')
    )
),

/* ---- 7) fonksiyonlar (eklenti sahibi olanlar hariç) ---------------------- */
fns as (
  select p.proname as obj, pg_get_functiondef(p.oid) || ';' as ddl
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.prokind in ('f','p')
    and not exists (select 1 from pg_depend d
                    where d.objid = p.oid and d.deptype = 'e')
),

/* ---- 8) view'lar --------------------------------------------------------- */
vws as (
  select c.relname as obj,
         'create or replace view public.' || quote_ident(c.relname) ||
         E' as\n' || pg_get_viewdef(c.oid, true) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'v'
),

/* ---- 9) trigger'lar ------------------------------------------------------ */
trg as (
  select cl.relname as obj, t.tgname as tname,
         pg_get_triggerdef(t.oid) || ';' as ddl
  from pg_trigger t
  join pg_class cl on cl.oid = t.tgrelid
  join pg_namespace n on n.oid = cl.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
),

/* ---- 10) RLS açık mı ----------------------------------------------------- */
rls as (
  select c.relname as obj,
         'alter table public.' || quote_ident(c.relname) ||
         ' enable row level security;' as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),

/* ---- 11) RLS politikaları ------------------------------------------------ */
pol as (
  select p.tablename as obj, p.policyname as pname,
         'create policy ' || quote_ident(p.policyname) ||
         ' on public.' || quote_ident(p.tablename) ||
         ' as ' || lower(p.permissive) ||
         ' for ' || lower(p.cmd) ||
         ' to ' || array_to_string(p.roles, ', ') ||
         coalesce(' using (' || p.qual || ')', '') ||
         coalesce(' with check (' || p.with_check || ')', '') || ';' as ddl
  from pg_policies p
  where p.schemaname = 'public'
),

/* ---- 12) PostgREST rollerine verilen yetkiler ---------------------------- */
grnt as (
  select g.table_name as obj, g.grantee || '.' || g.privilege_type as gname,
         'grant ' || lower(g.privilege_type) ||
         ' on public.' || quote_ident(g.table_name) ||
         ' to ' || quote_ident(g.grantee) || ';' as ddl
  from information_schema.role_table_grants g
  where g.table_schema = 'public'
    and g.grantee in ('anon','authenticated','service_role')
),

/* ---- 13) satır sayıları (hangi tablo seed taşıyor — INSERT'leri atlamak için)
   reltuples analyze edilmemiş tabloda -1 döner; gerçek count gerekli.
   query_to_xml düz select içinde dinamik sayım yapmanın standart yolu —
   salt okunur.                                                              */
counts as (
  select c.relname as obj,
         '--   ' || rpad(c.relname, 42) || ' ' ||
         lpad((xpath('/row/c/text()',
                query_to_xml('select count(*) as c from public.' || quote_ident(c.relname),
                             false, true, '')))[1]::text, 7) || ' satir' as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
)

select ddl from (
  select -1 sec, '' k1, 0 k2,
         '-- conventity.ORG public semasi · dokum: ' ||
         to_char(now(), 'YYYY-MM-DD HH24:MI') || ' UTC' as ddl
  union all select -1, '', 1, E'\n-- ============ -1 · KURULU EKLENTILER (bilgi) ============'
  union all select -1, exts.obj, 2, exts.ddl from exts
  union all select 0, '', 0, E'\n-- ===================== 0 · TIPLER ====================='
  union all select 0, types.obj, 1, types.ddl from types
  union all select 1, '', 0, E'\n-- ===================== 1 · DIZILER ====================='
  union all select 1, seqs.obj, 1, seqs.ddl from seqs
  union all select 2, '', 0, E'\n-- ===================== 2 · TABLOLAR ====================='
  union all select 2, tbls.obj, 1, tbls.ddl from tbls
  union all select 3, '', 0, E'\n-- ============ 3 · PK / UNIQUE / CHECK ============'
  union all select 3, cons.obj, 1, cons.ddl from cons
  union all select 4, '', 0, E'\n-- ===================== 4 · INDEKSLER ====================='
  union all select 4, idx.obj, 1, idx.ddl from idx
  union all select 5, '', 0, E'\n-- ===================== 5 · FONKSIYONLAR ====================='
  -- fonksiyonlar birbirini cagirabilir; govde dogrulamasini kapatinca
  -- alfabetik sira yeterli olur (pg_dump da boyle yapar).
  union all select 5, '', 1, 'set check_function_bodies = off;'
  union all select 5, fns.obj, 2, fns.ddl from fns
  union all select 6, '', 0, E'\n-- ===================== 6 · VIEW''LAR ====================='
  union all select 6, vws.obj, 1, vws.ddl from vws
  union all select 7, '', 0, E'\n-- ===================== 7 · TRIGGERLAR ====================='
  union all select 7, trg.obj, 1, trg.ddl from trg
  union all select 8, '', 0, E'\n-- ===================== 8 · RLS ====================='
  union all select 8, rls.obj, 1, rls.ddl from rls
  union all select 9, '', 0, E'\n-- ===================== 9 · POLITIKALAR ====================='
  union all select 9, pol.obj, 1, pol.ddl from pol
  union all select 10, '', 0, E'\n-- ===================== 10 · YETKILER ====================='
  union all select 10, grnt.obj, 1, grnt.ddl from grnt
  union all select 11, '', 0, E'\n-- ============ 11 · YABANCI ANAHTARLAR (en sonda) ============'
  union all select 11, fks.obj, 1, fks.ddl from fks
  union all select 12, '', 0, E'\n-- ====== 12 · SATIR SAYILARI (seed tespiti — DDL degil) ======'
  union all select 12, counts.obj, 1, counts.ddl from counts
) d
order by sec, k1, k2, ddl;
